id: P004546
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:41:01.026935
source_metadata:
  id: bdr:W3CN5423
  title: ཡ་ཆེན་ཨོ་རྒྱན་བསམ་གཏན་གླིང་གི་ཆོས་འབྱུང་།
  author: ''
  volumes:
    11337fb01b0648ac95d979a1428f7451:
      image_group_id: I3CN5425
      title: ''
      volume_number: 1
      total_pages: 366
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
