id: P004546
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5423
  title: ཡ་ཆེན་ཨོ་རྒྱན་བསམ་གཏན་གླིང་གི་ཆོས་འབྱུང་།
  author: ''
  volumes:
    11337fb01b0648ac95d979a1428f7451:
      image_group_id: I3CN5425
      title: ''
      volume_number: 1
      total_pages: 366
