id: I98321685
legacy_id: P004546
ocr_import_info:
  bdrc_scan_id: W3CN5423
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T17:53:07'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T15:09:05.588096+00:00'
last_modified: 2022-09-03 23:09:18.219305
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN5423
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3CN5423
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཡ་ཆེན་ཨོ་རྒྱན་བསམ་གཏན་གླིང་གི་ཆོས་འབྱུང་།
  author: རྒྱལ་རྩེ་ཨརྱ་དེ་བ།
statistics:
  ocr_word_mean_confidence_index: 0.9655541858964938
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I3CN5425:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN5425
      total_pages: 366
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN5425.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9655541858964938
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
