id: I98321685
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:55:18+00:00'
last_modified: '2022-06-08T01:50:47.404888+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5423
  title: ཡ་ཆེན་ཨོ་རྒྱན་བསམ་གཏན་གླིང་གི་ཆོས་འབྱུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    107B:
      image_group_id: I3CN5425
      title: ''
      total_pages: 366
      order: 1
      base_file: 107B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
